apiVersion: v1
kind: Service
metadata:
  name: mern-todo-backend
  namespace: mern-todo
  labels:
    app: mern-todo
    component: backend
spec:
  type: ClusterIP
  selector:
    app: mern-todo
    component: backend
  ports:
  - name: http
    port: 5000
    targetPort: 5000
    protocol: TCP
  sessionAffinity: None
